apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: cnpg
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: cnpg.promise.dinova.services
    spec:
      group: promise.dinova.services
      names:
        kind: cnpg
        plural: cnpg
        singular: cnpg
      scope: Namespaced
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  name:
                    type: string
                  storage:
                    type: string
                type: object
            type: object
        served: true
        storage: true
  #dependencies:
  workflows:
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
        spec:
          containers:
          - image: karavy/kratix:0.0.1
            name: create-cnpg-instance
status: {}
