apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: jenkins
  namespace: default
spec:
  #dependencies:
  api:
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: cnpg.promise.dinova.services
  spec:
    group: cnpg.promise.dinova.services
    scope: Namespaced
    names:
      plural: cnpg
      singular: cnpg
      kind: cnpg
    versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  name:
                    type: string
                  cpu:
                    type: string
                  memory:
                    type: string
                  storage:
                    type: string

  #workflows:
