#!/usr/bin/env sh

set -x

# Add logic for pipeline here.
# Example:
# name="$(yq eval '.metadata.name' /input/object.yaml)"
# sed "s/TBDNAME/${name}/g" /tmp/transfer/filename.yaml > /output/filename.yaml

#Get the name from the Promise Custom resource
name=$(yq eval '.spec.name' /kratix/input/object.yaml)
storage=$(yq eval '.spec.storage' /kratix/input/object.yaml)
cpu=$(yq eval '.spec.cpu' /kratix/input/object.yaml)
memory=$(yq eval '.spec.memory' /kratix/input/object.yaml)

# Inject the name into the Jenkins resources
find /tmp/transfer -type f -exec sed -i \
  -e "s/<name>/${name}/g" \
  {} \;

find /tmp/transfer -type f -exec sed -i \
  -e "s/<storage>/${storage}/g" \
  {} \;


find /tmp/transfer -type f -exec sed -i \
  -e "s/<memory>/${memory}/g" \
  {} \;

find /tmp/transfer -type f -exec sed -i \
  -e "s/<cpu>/${cpu}/g" \
  {} \;

cp /tmp/transfer/* /kratix/output/

git config --global user.email "kratix@platform.local"
git config --global user.name "Kratix Promise"

# Usa SSH oppure HTTPS con token
GIT_SSH_COMMAND="ssh -i /kratix-input/ssh-key -o StrictHostKeyChecking=no" \

# (3) Copia output della Promise
currdate=$(date +%F-%H%M%S)
mkdir -p postgres/currdate
cp /kratix/output/* postgres/currdate

cd postgres/currdate

echo '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA6pHyTlFA/3idmIEiM3OL2XWByxouTJGzSqeO/yR4q1DK1twCsZhZ
ZVT6b+o2IwsXUK3J92wFCDG3blBEulBAchuJezmTvYgERqB9aQ0/ubGfCcgB2NoKhbXSBF
u3w7U9amQ27XtTfajNzT9Ug3vIfxG7OP6pmoNtqV20CSKYC1zMAOZHK7Q91SUB+TDHpjlq
PaAlwHLOG3llt6twUSx8qxuepmvVCFeMwTLE3YPYPvKLVlBnzjqN4+5XBKwNAJ1BkiR4YH
HvS/AJp7mRSLrBI+/njpkO4eW/LQ9OHRxQwBeaw0Ig08r78pBJfQLAne+cb30R3Dr2DjgO
0zZNypGmULZBNTrJhVJv9bq4XTYcQGe34VHUkTj+EEUp+bxLMLBMHIMjz/Fq2Z+K3rt5ob
StC6Tym3KgQDWmbUeM3BB5a4Qt3pNCavqcjI4hlLIEGogup6hY3dYdbkRAtgXZagQfA7pY
X5x7gv21N3Q3ucut323OT7f+uQ2laBC2w4gkebalAAAFiEwi0ARMItAEAAAAB3NzaC1yc2
EAAAGBAOqR8k5RQP94nZiBIjNzi9l1gcsaLkyRs0qnjv8keKtQytbcArGYWWVU+m/qNiML
F1CtyfdsBQgxt25QRLpQQHIbiXs5k72IBEagfWkNP7mxnwnIAdjaCoW10gRbt8O1PWpkNu
17U32ozc0/VIN7yH8Ruzj+qZqDbaldtAkimAtczADmRyu0PdUlAfkwx6Y5aj2gJcByzht5
ZbercFEsfKsbnqZr1QhXjMEyxN2D2D7yi1ZQZ846jePuVwSsDQCdQZIkeGBx70vwCae5kU
i6wSPv546ZDuHlvy0PTh0cUMAXmsNCINPK+/KQSX0CwJ3vnG99Edw69g44DtM2TcqRplC2
QTU6yYVSb/W6uF02HEBnt+FR1JE4/hBFKfm8SzCwTByDI8/xatmfit67eaG0rQuk8ptyoE
A1pm1HjNwQeWuELd6TQmr6nIyOIZSyBBqILqeoWN3WHW5EQLYF2WoEHwO6WF+ce4L9tTd0
N7nLrd9tzk+3/rkNpWgQtsOIJHm2pQAAAAMBAAEAAAGAB3Y0j8a4a1gGJV2IPbxBeN2qzw
/qZJ+m5StO2nFp0ENN7IdLo6QdxeIt5ET+S1+VMokQuWjrgQ75z43IneejIS4ckbmraDZN
MoT08FROUGUk0r4UxvXqq0W1JFPZlOVtSnbdI3FOntrxjwOid9tGbbpd6wp40TQ4lxBmw3
qg/Q2K5MVugqalZ+QZO7jQRQqjBUpUoRpV0ZxrPqw6sq5YWeYTRiZ8fJsyXEv15LkGtjvn
cEu2/aGxtUw14u1pLXmTFozZ6i0iLggDuwPArm6B7cr32U2yCJsA5kD1dlpJAtf25zClCh
RQY8daZJTyS49x7ntWbCSoVmdPbNf941H3wdSMxw4bpxBcNvkDAVLhdB+T2uyHfNCpzgjb
V48aaLFPSQbK6vAjKR7XATYy7ErnRLJG8IKwPls7RprTU54TVLEPShHu3typRxMcolg7fL
kjPCGSmgCbUaNZs0dd/JJwJaEMQ/G1Os3tKxUrXXcOLnZcko585WPvyi2H5iB4VTcpAAAA
wE3RGfpVdehYo1QNqL7buZrwmrzTLSfJKDZNlFBS2jsN7gFVGlTXtGClhYfHI2iT803eVp
Ow3oaD+5tqBYeZT0ge0rprQjMm3b8NQPgp33nB6964mqIb22yFqlFZ6pSokwRksd5FFfHY
tzByPVt33vnhdY8Ip1G0XFcLp86NrZ652P+ytU7IORJMYjC+zKkQ1GFRyr+nDJ0Ewz0aDO
vZDjXW8gJwVaFf3T8voKJBnXLMUVXahH+k1mN3wJ3cN7A3owAAAMEA/+tnxvXHWRD8EXEL
a8aL46FUATsXNUh3DXQIGHDzqil7MKw0qjytq8gLK0zlkzqDsW6yTg5QiNo27uyt+YJ4am
gsiVzAY3z8N/u0tkrX1SmBSgqTVF7bkkj7ZhTYR+G/XvULgTVE/hynUPXv/KytSK95q9uU
Dhmnen4NNJ/RlTLk7nIEApOH/zFnii++gC8ZezY/t1tI2idDyw2LqkXFC1oeBm8AFwCQ5e
8Ur0rKPdVph8oSUEmUdyFwmo9LIFT9AAAAwQDqpNK07JAuxanXjTvymrTcfGxoffH9Gllv
1zuqQsH6VawAi0W+3R09FQgU8iIUKfgeQ80vLnXOmLbuxCWQq5TzYDXvshxEbh2HIqK5cd
FzQG0cxbckNn5hibB5oMKo/LlV75oqz2oxWJHy/gnIqd450f+MBF3hb2Ohg5rsANM2guWk
H0lM7EwejUw8Ubn9H1fB+VxXa1lqELpoXhmhHXYNOjRkyQNjAWmTFScjYSizu7GCFNsURZ
BMOaYLdKIBrMkAAAAQcm9vdEBtaW5pby1jcC0wMQECAw==
-----END OPENSSH PRIVATE KEY-----' > /kratix-input/ssh-key

# (4) Commit & push
git init
git add .
git commit -m "Add output for postgres instance $(date)"
git branch -M main
git remote add origin git@github.com:karavy/test1.git
git push -u origin main
